# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28ff0340135439782c58cf68191d7c4dd93e144027d78dc28503308f222f433a9ce344cd6bd6de508bf424f6601329501666b536409976e3b4e20d6d7da982d9

test:
  secret_key_base: 640fd52c8e5fc96c9157569597fb3648d207aae7c37d7ce2723d1983b7f7015933679781d1e078f7c17012f0a7b4f07af8e1d4c8b50cdf10ac77e70c068fd3ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
